/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nhans' at '7/26/17 6:12 PM' with Gradle 2.14.1
 *
 * @author nhans, @date 7/26/17 6:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
