import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nhans' at '7/26/17 6:12 PM' with Gradle 2.14.1
 *
 * @author nhans, @date 7/26/17 6:12 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
